### ISSUE TITLE
Server response is 404

### ISSUE THREAD

**Issue by The224** [luispabon/kong-certbot-agent#38]
## Using
- Kong 1.1.x (as DB-Less)
- docker-compose 1.24.0

---

## Problem

I get a `404` from kong-certbot when I try to get a certificate.

```
Invalid response from http://domain/.well-known/acme-challenge/rxvaWacypC-621kBKc-b0W4nRPgdlhuv21ZUQY30jjE [ip]: 404
```

But `http://domain/.well-known/acme-challenge` return `ACME client standalone challenge solver`.

---
## Config files

My `kong.yml`:

```
# Kong Cerbot Agent
- name: Kong-Cerbot-Agent
  url: http://kong-certbot-agent
  routes:
  - name: Certbot
    hosts:
    - domain
    paths:
    - /.well-known/acme-challenge
    regex_priority: 0
    preserve_host: false
    strip_path: false
    protocols:
    - http
    methods:
    - GET
```

My `docker-compose.yml` `kong-certbot-agent`:
```
  # Kong Certbot (Let's Encrypt)
  kong-certbot-agent:
    image: "phpdockerio/kong-certbot-agent"
    user: "${KONG_USER:-root}"
    container_name: kong-certbot
    # command: ./certbot-agent certs:update http://kong:8001 contact@domain ${LIST_ALL_DOMAIN}
    command: [ "./certbot-agent", "certs:update", "http://kong:8001", "contact@domain", "${LIST_ALL_DOMAIN}", "--test-cert" ]
    volumes:
      - ~/kong-certbot-agent/letsencrypt:/etc/letsencrypt
      - ~/kong-certbot-agent/log:/var/log/letsencrypt
```
